on: [push]
env:
  BUILD_NUMBER: ${{github.run_number}}
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Display version
        run: echo $BUILD_NUMBER
